export default function HowItWorksPage() {
  return <main className="directory-page how-page">
    <nav className="site-nav directory-nav" aria-label="Main navigation"><a className="brand" href="/"><span className="brand-mark">+</span> mendwell</a><div className="nav-links"><a href="/directory">Find a psychologist</a><a className="nav-current" href="/how-it-works">How it works</a><a href="/#about">About us</a><a href="/account">User accounts</a></div><a className="provider-link" href="/professionals/apply">Professional registration <span aria-hidden="true">↗</span></a></nav>
    <section className="how-intro"><p className="eyebrow">A more human way to find care</p><h1>Good care begins<br /><em>with a good fit.</em></h1><p>We make the first step clearer by bringing trusted professionals, thoughtful details, and your own pace into one place.</p></section>
    <section className="how-steps"><div className="how-step"><span>01</span><div><p className="eyebrow">Start with what matters</p><h2>Tell us what you&apos;re<br /><em>carrying.</em></h2><p>Search by the things you are moving through, from anxiety and grief to relationships and life transitions. You do not need the perfect words.</p></div></div><div className="how-step"><span>02</span><div><p className="eyebrow">Look for the right feeling</p><h2>Meet professionals<br /><em>with context.</em></h2><p>Read about each psychologist&apos;s approach, training, languages, and ways of working. Fit is personal, so the details should be visible.</p></div></div><div className="how-step"><span>03</span><div><p className="eyebrow">Move at your pace</p><h2>Take one small<br /><em>next step.</em></h2><p>Save a profile, request a consultation, or simply come back later. There is no pressure to decide everything today.</p></div></div></section>
    <section className="how-trust"><div><p className="eyebrow">Our promise</p><h2>Clarity without<br /><em>the coldness.</em></h2></div><div><p>Every professional on Mendwell is reviewed through a careful verification process. We believe trust is built through transparency, not just a badge.</p><a className="dark-button" href="/directory">Explore professionals <span aria-hidden="true">→</span></a></div></section>
    <footer className="site-footer"><div><a className="brand footer-brand" href="/"><span className="brand-mark">+</span> mendwell</a><p>A gentler place to begin.</p></div><div className="footer-column"><p className="eyebrow">Contact</p><a href="tel:+254721650402">+254 721 650 402</a><a href="mailto:sam.clinicalpsychology@gmail.com">sam.clinicalpsychology@gmail.com</a></div><div className="footer-column"><p className="eyebrow">Stay connected</p><a href="https://wa.me/250795689260?text=Welcome%20to%20Mendwell%20Services%2C%20Connecting%20Clients%20with%20Psychologists.%0A%0A" target="_blank" rel="noreferrer">WhatsApp <span aria-hidden="true">↗</span></a><a href="https://web.facebook.com/psalm.chrisam/" target="_blank" rel="noreferrer">Facebook <span aria-hidden="true">↗</span></a><a href="https://www.instagram.com/alosisam/" target="_blank" rel="noreferrer">Instagram <span aria-hidden="true">↗</span></a></div></footer>
  </main>;
}
